name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Install requirements
        run: |
          cd app
          pip install -r requirements.txt
          
          
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test main.py
      - run: |
          cd app 
          python3 main.py
          python3 main.py --name=Friend!
